version: '3.7'

services:
 postgres_inventario:
   container_name: postgres_inventario_qk
   image: postgres:15.1
   environment:
      POSTGRES_USER: inventario
      POSTGRES_PASSWORD: inventario
   ports:
     - "5432:5432"
     
 prometheus:
    image: prometheus-quarkus
    container_name: prometheus_inventario_qk
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
 grafana:
    image: grafana/grafana-enterprise
    container_name: grafana_inventario_qk
    ports:
      - "3000:3000"
    depends_on:
      - prometheus